# Generated by Django 5.0.6 on 2024-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('schedule_datetime', models.DateTimeField()),
                ('command', models.CharField(max_length=10000)),
                ('output', models.CharField(max_length=10000)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
